#!/usr/bin/env tsx
// =============================================================================
// scripts/snapshot_schema.ts
// =============================================================================
// Captures a schema-only dump of a database after a successful migration.
// Writes a timestamped snapshot and updates schema_latest.sql.
//
// Supports Postgres (pg_dump) and MySQL (mysqldump).
// Metadata header is prepended to each snapshot file.
//
// Usage:
//   INSTANCE=instance-1 DB=db-orders DB_TYPE=postgres \
//   DB_HOST=localhost DB_PORT=5432 DB_USER=app DB_PASS=secret \
//   tsx scripts/snapshot_schema.ts
// =============================================================================

import { execSync }                   from 'child_process';
import { writeFileSync, mkdirSync,
         readFileSync, existsSync }   from 'fs';
import { join }                       from 'path';

// ── Config from environment ────────────────────────────────────────────────
const INSTANCE = process.env.INSTANCE ?? '';
const DB       = process.env.DB       ?? '';
const DB_TYPE  = process.env.DB_TYPE  ?? '';
const DB_HOST  = process.env.DB_HOST  ?? '';
const DB_PORT  = process.env.DB_PORT  ?? '5432';
const DB_USER  = process.env.DB_USER  ?? '';
const DB_PASS  = process.env.DB_PASS  ?? '';

for (const [k, v] of Object.entries({ INSTANCE, DB, DB_TYPE, DB_HOST, DB_USER, DB_PASS })) {
  if (!v) { console.error(`ERROR: ${k} is required`); process.exit(1); }
}

// ── Paths ──────────────────────────────────────────────────────────────────
const timestamp     = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19).replace('T', '_');
const schemaDir     = join('schemas', INSTANCE, DB);
const versionedFile = join(schemaDir, `schema_${timestamp}.sql`);
const latestFile    = join(schemaDir, 'schema_latest.sql');

mkdirSync(schemaDir, { recursive: true });

console.log('─'.repeat(52));
console.log('  Schema Snapshot');
console.log(`  Instance : ${INSTANCE}`);
console.log(`  Database : ${DB}`);
console.log(`  Type     : ${DB_TYPE}`);
console.log(`  Output   : ${versionedFile}`);
console.log('─'.repeat(52));

// ── Capture dump ───────────────────────────────────────────────────────────
let dumpSql = '';

if (DB_TYPE === 'postgres') {
  const env = { ...process.env, PGPASSWORD: DB_PASS };
  dumpSql = execSync(
    `pg_dump ` +
    `--host=${DB_HOST} --port=${DB_PORT} --username=${DB_USER} ` +
    `--dbname=${DB} --schema-only --no-owner --no-acl --no-comments`,
    { env, encoding: 'utf-8' }
  );

} else if (DB_TYPE === 'mysql' || DB_TYPE === 'mariadb') {
  dumpSql = execSync(
    `mysqldump ` +
    `--host=${DB_HOST} --port=${DB_PORT} ` +
    `--user=${DB_USER} --password=${DB_PASS} ` +
    `--no-data --routines --triggers --single-transaction ` +
    `--set-gtid-purged=OFF ${DB}`,
    { encoding: 'utf-8' }
  );

} else {
  console.error(`ERROR: Unsupported DB_TYPE '${DB_TYPE}'`);
  process.exit(1);
}

// ── Prepend metadata header ────────────────────────────────────────────────
const header = [
  `-- ============================================================`,
  `-- Schema snapshot`,
  `-- Instance : ${INSTANCE}`,
  `-- Database : ${DB}`,
  `-- Captured : ${new Date().toISOString()} UTC`,
  `-- DB type  : ${DB_TYPE}`,
  `-- Host     : ${DB_HOST}:${DB_PORT}`,
  `-- Generated by: scripts/snapshot_schema.ts`,
  `-- DO NOT EDIT — this file is auto-generated.`,
  `-- ============================================================`,
  '',
].join('\n');

const fullContent = header + dumpSql;

writeFileSync(versionedFile, fullContent, 'utf-8');
writeFileSync(latestFile,    fullContent, 'utf-8');

console.log(`\n✓ Snapshot written  : ${versionedFile}`);
console.log(`✓ Latest updated    : ${latestFile}`);
console.log('Done.\n');
